# This file is for OSD-GCP installation only.
# It is applied by `helm upgrade` after the `values-showcase.yaml` is applied and only contains complementary differences for OSD-GCP.
# Note, that it overwrites the whole key that is present in this file.
# The only exception is global.dynamic.plugins, that gets merged with the base file.

# Disable orchestrator for OSD-GCP due to infrastructure limitations
orchestrator: null
